=== imace/de.cau.cs.kieler/plugins/de.cau.cs.kieler.core.ui.examplewizard/resources/examplesstore.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio Developer Edition (Trial) 8.0.8.2044 (http://www.liquid-technologies.com)-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Examples">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="Example">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="ExampleType" />
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ExampleType">
		<xs:sequence>
			<xs:element name="ID" type="xs:string" />
			<xs:element name="Name" type="xs:string" />
			<xs:element name="PackageName" type="xs:string" />
			<xs:element name="PluginID">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="Version" type="xs:string" use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Version" type="xs:string" />
			<xs:element minOccurs="0" name="Description" type="xs:string" />
			<xs:element minOccurs="0" maxOccurs="unbounded" name="File" type="FileType" />
			<xs:element minOccurs="0" name="Category" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FileType">
		<xs:sequence>
			<xs:element name="FileName" type="xs:string" />
			<xs:element minOccurs="0" name="TargetFolder" type="xs:string" />
			<xs:element name="ShowInEditor" type="xs:boolean" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== imace/de.cau.cs.kieler/plugins/de.cau.cs.kieler.core.ui.examplewizard/resources/examplestore.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio Developer Edition (Trial) 8.0.8.2044 (http://www.liquid-technologies.com) -->
<Examples xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Vertigo\kieler\de.cau.cs.kieler.core.ui.examplewizard\resources\examplesstore.xsd">
	<Example>
		<ID>example</ID>
		<Name>Test Example</Name>
		<PackageName>example</PackageName>
		<PluginID Version="someversion">someid</PluginID>
		<Version>201002274536</Version>
		<Description>This is a Test Example</Description>
		<File>
			<FileName>Test1.txt</FileName>
			<ShowInEditor>true</ShowInEditor>
		</File>
		<File>
			<FileName>Test2.txt</FileName>
			<ShowInEditor>false</ShowInEditor>
		</File>
		<File>
			<FileName>Test3.txt</FileName>
			<ShowInEditor>true</ShowInEditor>
		</File>
	</Example>
	<Example>
		<ID>string</ID>
		<Name>string</Name>
		<PackageName>string</PackageName>
		<PluginID Version="string">string</PluginID>
		<Version>string</Version>
		<File>
			<FileName>string</FileName>
			<ShowInEditor>false</ShowInEditor>
		</File>
		<File>
			<FileName>string</FileName>
			<TargetFolder>string</TargetFolder>
			<ShowInEditor>1</ShowInEditor>
		</File>
		<File>
			<FileName>string</FileName>
			<TargetFolder>string</TargetFolder>
			<ShowInEditor>0</ShowInEditor>
		</File>
		<Category>string</Category>
	</Example>
	<Example>
		<ID>string</ID>
		<Name>string</Name>
		<PackageName>string</PackageName>
		<PluginID Version="string">string</PluginID>
		<Version>string</Version>
	</Example>
	<Example>
		<ID>string</ID>
		<Name>string</Name>
		<PackageName>string</PackageName>
		<PluginID Version="string">string</PluginID>
		<Version>string</Version>
		<File>
			<FileName>string</FileName>
			<TargetFolder>string</TargetFolder>
			<ShowInEditor>false</ShowInEditor>
		</File>
		<File>
			<FileName>string</FileName>
			<TargetFolder>string</TargetFolder>
			<ShowInEditor>true</ShowInEditor>
		</File>
		<File>
			<FileName>string</FileName>
			<ShowInEditor>false</ShowInEditor>
		</File>
		<File>
			<FileName>string</FileName>
			<ShowInEditor>0</ShowInEditor>
		</File>
	</Example>
</Examples>
